version: '2'

networks:
  nginxphp-isol:
    driver: bridge
  # needed for independent services coming up in docker
  # to be able to be proxied with nginx
  #nginx-pool:
  #  external: true

services:
  web:
    image: nginx:stable
    ports:
      - 80:80
      - 443:443
    volumes:
      # customization includes
      - ./nginx/etc/nginx/conf.d/custom.conf:/etc/nginx/conf.d/custom.conf:ro

      # feature configs
      - ./nginx/etc/nginx/includes:/etc/nginx/includes:ro

      # webroot
      - ./www:/var/www/html:ro

      # website configurations
      - ./nginx/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro

      # ssl certificate
      - ./nginx/ssl/nginx.key:/etc/ssl/private/nginx.key:ro
      - ./nginx/ssl/nginx.crt:/etc/ssl/certs/nginx.crt:ro

    restart: always
    depends_on:
      - php
    networks:
      - nginxphp-isol
#      - nginx-pool

  php:
    image: php:7-fpm
    volumes:
      - ./www:/var/www/html:ro
    restart: always
    networks:
      - nginxphp-isol
